### ISSUE TITLE
400 Bad request from Gerrit 2.14.6 using PyGerrit2 from GitHub master

### ISSUE THREAD

**Issue by agawande** [dpursehouse/pygerrit2#18]
Hi, I use PyGerrit2 as such:
https://github.com/agawande/NLSR-minindn-tester-bot/blob/master/src/testNlsr.py#L31
(I am using the latest PyGerrit2 from GitHub master installed using sudo python setup.py install)

I was getting 400 Bad request from Gerrit (2.14.6):
```
args after first merge_dict {}
Posting args:  {'verify': True, 'data': '{"labels": {"Verified-Integration": -1}, "message": "NLSR tester bot: Test Standalone test w/security failed!"}', 'auth': <pygerrit2.rest.auth.HTTPBasicAuthFromNetrc object at 0x7fd069805850>, 'headers': {'Accept-Encoding': 'gzip', 'Accept': 'application/json'}}
Got response
response:  <Response [400]>
response.text:  Expected Content-Type: application/json

Traceback (most recent call last):
  File "testNlsr.py", line 176, in <module>
    TEST.get_and_test_changes()
  File "testNlsr.py", line 156, in get_and_test_changes
    self.rest.review(change_id, patch, self.rev)
  File "/usr/local/lib/python2.7/dist-packages/pygerrit2/rest/__init__.py", line 265, in review
    self.post(endpoint, data=str(review))
  File "/usr/local/lib/python2.7/dist-packages/pygerrit2/rest/__init__.py", line 213, in post
    decoded_response = _decode_response(response)
  File "/usr/local/lib/python2.7/dist-packages/pygerrit2/rest/__init__.py", line 47, in _decode_response
    response.raise_for_status()
  File ".local/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://gerrit.named-data.net/a/changes/I5124e9fd49bd9850c904c31d221b42b4249553a3/revisions/7/review
```
```
So under post method in pygerrit/2rest/__init__.py I did:
       #if ("data" in kwargs and isinstance(kwargs["data"], dict)) or \
        #        "json" in kwargs:
        _merge_dict(
            args, {
                "headers": {
                    "Content-Type": "application/json;charset=UTF-8"
                }
            }
        )
```
And then it was successfully able to post:
```
{"labels": {"Verified-Integration": -1}, "message": "NLSR tester bot: Test Standalone test w/security failed!"}
args after first merge_dict {'headers': {'Content-Type': 'application/json;charset=UTF-8'}}
Posting args:  {'headers': {'Content-Type': 'application/json;charset=UTF-8', 'Accept-Encoding': 'gzip', 'Accept': 'application/json'}, 'data': '{"labels": {"Verified-Integration": -1}, "message": "NLSR tester bot: Test Standalone test w/security failed!"}', 'auth': <pygerrit2.rest.auth.HTTPBasicAuthFromNetrc object at 0x7f9ab8ace850>, 'verify': True}
Got response
response:  <Response [200]>
response.text:  )]}'
{"labels":{"Verified-Integration":-1}}

```

**Comment by dpursehouse** [comment]
This is a known issue with `post` requests that include json content.  A workaround is to pass the json in the `json` parameter rather than `data`.

**Comment by dpursehouse** [comment]
I'm planning to do some changes that will fix this without having to do the workaround
